### ISSUE TITLE
Compatibility with markdown-it-attrs?

### ISSUE THREAD

**Issue by f0rr0** [arve0/markdown-it-implicit-figures#13]
This 

``` md
![Stuff](./salty_egg.jpg) {.full-width}
```

produces

``` html
<p class="full-width">
  <img src="./salty_egg.jpg" alt="Stuff">
</p>
```

instead of:

``` html
<fig class="full-width">
  <img src="./salty_egg.jpg" alt="Stuff">
  <figcaption>Stuff</figcaption>
</fig>
```

**Comment by arve0** [comment]
Thanks for reporting.

It's because markdown-it-attrs does not remove `{}` from `token.content`:

```md
[caption](img.png "title"){.asdf}
```

```js
[ Token {
    type: 'paragraph_open',
    tag: 'p',
    attrs: null,
    map: [ 0, 1 ],
    nesting: 1,
    level: 0,
    children: null,
    content: '',
    markup: '',
    info: '',
    meta: null,
    block: true,
    hidden: false },
  Token {
    type: 'inline',
    tag: '',
    attrs: null,
    map: [ 0, 1 ],
    nesting: 0,
    level: 1,
    children: [ [Object] ],
    content: '![caption](img.png "title"]{.asdf}',
    markup: '',
    info: '',
    meta: null,
    block: true,
    hidden: false },
  Token {
    type: 'paragraph_close',
    tag: 'p',
    attrs: null,
    map: null,
    nesting: -1,
    level: 0,
    children: null,
    content: '',
    markup: '',
    info: '',
    meta: null,
    block: true,
    hidden: false } ]
```

**Comment by arve0** [comment]
Thanks for reporting. Fixed in markdown-it-attrs 0.7.1.

**Comment by coryschires** [comment]
@arvo Thanks for all your hard work on this plugin!

Unfortunately, I'm still encountering the problem described above – even when using all the latest versions of `markdown-it`, `markdown-it-implicit-figures`, and `markdown-it-attrs`. 

I've recreated this issue in this fiddle: https://jsfiddle.net/xsywjrzr/1/

Thanks again and let me know if there's anything I can do to help!

**Comment by arve0** [comment]
Hm, strange. I'm currently away from the computer, so unable to look into it. Feel free to poke around in the code. 

I'll be back later this week.

**Comment by arve0** [comment]
See #18. Fixed in markdown-it-attrs 0.9.0.
